
/* BOMB1 */
static char *bomb1[] = {
"16 16 7 1 ",
"  c None",
". c #000000",
"X c #272338",
"o c #373446",
"O c #5A576A",
"+ c #FFAA62",
"@ c #FFE762",
"        . @     ",
"      ...+      ",
"    ..oo@o@.    ",
"   .oooooooo.   ",
"  .oOOooooooX.  ",
"  .OOoooooooX.  ",
" .oOooooooooXX. ",
" .oOooooooooXX. ",
" .oooooooooXXX. ",
" .oooooooooXXX. ",
"  .oooooooXXX.  ",
"  .XXoooXXXXX.  ",
"   .XXXXXXXX.   ",
"    ..XXXX..    ",
"      ....      ",
"                "
};

/* BOMB2 */
static char *bomb2[] = {
"16 16 7 1 ",
"  c None",
". c #000000",
"X c #272338",
"o c #373446",
"O c #5A576A",
"+ c #FFAA62",
"@ c #FFE762",
"         .. @   ",
"        .  +    ",
"      ....@ @   ",
"    ..oooo..    ",
"   .oOOooooo.   ",
"   .oOoooooX.   ",
"  .oOooooooXX.  ",
"  .oOooooooXX.  ",
"  .oooooooXXX.  ",
"  .oooooooXXX.  ",
"   .XoooXXXX.   ",
"   .XXXXXXXX.   ",
"    ..XXXX..    ",
"      ....      ",
"                ",
"                "
};

/* BOMB3 */
static char *bomb3[] = {
"16 16 7 1 ",
"  c None",
". c #000000",
"X c #272338",
"o c #373446",
"O c #5A576A",
"+ c #FFAA62",
"@ c #FFE762",
"          .     ",
"         . . @  ",
"        .   +   ",
"      .... @ @  ",
"    ..oooo..    ",
"    .oOoooo.    ",
"   .oOoooooX.   ",
"   .oOoooooX.   ",
"   .oooooooX.   ",
"   .ooooooXX.   ",
"    .XooXXX.    ",
"    ..XXXX..    ",
"      ....      ",
"                ",
"                ",
"                "
};

/* BRICK */
static char *brick[] = {
"16 16 4 1 ",
"  c #000000",
". c #081327",
"X c #11264D",
"o c #515F78",
"oooooooooooooooX",
"oXXXX.oXXXXXXXX.",
"oXXXX.oXXXXXXXX.",
"o...............",
"ooooooooooooooo.",
"oXXXXXXXXXX.oXX.",
"oXXXXXXXXXX.oXX.",
"o...............",
"oooooooo.oooooo.",
"oXXXXXXX.oXXXXX.",
"oXXXXXXX.oXXXXX.",
"o...............",
"ooooooooooooooo.",
"oXXXXXXXXXXXXXX.",
"oXXXXXXXXXXXXXX.",
"X.............. "
};

/* EXPLOSION_1_CENTER */
static char *explosion_1_center[] = {
"16 16 3 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"                ",
"                ",
"                ",
"                ",
"                ",
"       ..       ",
"     ..XX.      ",
"     .XXXX.     ",
"     .XXXX.     ",
"      .XX.      ",
"       ...      ",
"                ",
"                ",
"                ",
"                ",
"                "
};

/* EXPLOSION_2_CENTER */
static char *explosion_2_center[] = {
"16 16 5 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"o c #FFB700",
"O c #FF9425",
"                ",
"                ",
"       ..       ",
"      .XX..     ",
"    ..XXXXX.    ",
"    .XXOOXX.    ",
"   .XXOOOOXX.   ",
"  .XXXOooOOXX.  ",
"  .XXOOooOOXX.  ",
"   .XXOOOOXX.   ",
"    .XXOOXX.    ",
"     .XXXX.     ",
"     .XXX.      ",
"      ...       ",
"                ",
"                "
};

/* EXPLOSION_3_ARM */
static char *explosion_3_arm[] = {
"16 16 3 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
".......        .",
"XXXXXXX........X",
"...XXXXXXXX.....",
"   .........    ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                "
};

/* EXPLOSION_3_CENTER */
static char *explosion_3_center[] = {
"16 16 5 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"o c #FFB700",
"O c #FF9425",
"      .XX.      ",
"      .XX.      ",
"     .XXXX.     ",
"     .XOOX.     ",
"    .XOOOXX.    ",
"   .XXOoOOXX..  ",
"...XXOOooOOXXX..",
"XXXXOOooooOOOXXX",
"XXXXOOooooOOXXXX",
"...XXOOoOOXXX...",
"   .XXOOOXX..   ",
"    .XXOOX.     ",
"     .XXXX.     ",
"      .XX.      ",
"      .XX.      ",
"      .XX.      "
};

/* EXPLOSION_3_HAND */
static char *explosion_3_hand[] = {
"16 16 3 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"      ......... ",
"     .XXXXXXXXX.",
"      ..XXXX....",
"        ....    ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                "
};

/* EXPLOSION_4_ARM */
static char *explosion_4_arm[] = {
"16 16 5 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"o c #FFB700",
"O c #FF9425",
"                ",
"                ",
"                ",
"                ",
"  ...         ..",
"..XXX.....  ..XX",
"XXOOXXXXXX..XXXO",
"oooooOOOOXXXOOOo",
"OoooooooooooOOOo",
"XOOOOooooOOOOXXO",
".XXXOOOOXXXXXXXX",
" ..XXXXX........",
"   .....        ",
"                ",
"                ",
"                "
};

/* EXPLOSION_4_CENTER */
static char *explosion_4_center[] = {
"16 16 7 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"o c #FFB700",
"O c #FF9425",
"+ c #FFE800",
"@ c #FFF66A",
"    .XOooOX.    ",
"    .XOooOX.    ",
"    .XOooOX.    ",
"   .XXOooOOX.   ",
"...XXOooooOOX...",
"XXXOOOo++ooOXXXX",
"OOOOoo++++ooOOOO",
"ooooo++@@++ooooo",
"oooo++@@@@++oooo",
"OOooo+@@@@+ooOOO",
"XXOOoo++@+oOOXXX",
"..XXOoo+++oOXX..",
"  .XOOo+ooOX..  ",
"   .XOoooOX.    ",
"   .XOOooOX.    ",
"    .XOooOX.    "
};

/* EXPLOSION_4_HAND */
static char *explosion_4_hand[] = {
"16 16 5 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"o c #FFB700",
"O c #FF9425",
"                ",
"                ",
"                ",
"                ",
"      ....      ",
"     .XXXX......",
"    .XXOOOXXXXXX",
"    .XOOooOOOOOo",
"    .XXOOoooooOO",
"     .XXXOOOXXXX",
"      ..XXXXX...",
"        .....   ",
"                ",
"                ",
"                ",
"                "
};

/* EXPLOSION_5_ARM */
static char *explosion_5_arm[] = {
"16 16 7 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"o c #FFB700",
"O c #FF9425",
"+ c #FFE800",
"@ c #FFF66A",
"                ",
"                ",
" ........     ..",
".XXXXXXXX.....XX",
"XXOOOOOOXXXXXXXO",
"OOOooooOOOOOOOOO",
"ooo++++oooOOOooo",
"++++@@+++++oo+++",
"+++@@@@+++++++++",
"Oo++++++oooo++++",
"XOo++ooOOOOOOo++",
"XOOooOOXXXXXXOoO",
".XXOOXXX.....XOO",
" ..XXX..     ..X",
"   ...         .",
"                "
};

/* EXPLOSION_5_CENTER */
static char *explosion_5_center[] = {
"16 16 8 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"o c #FFB700",
"O c #FF9425",
"+ c #FFE800",
"@ c #FFF66A",
"# c #FFFDD9",
"  .XOOo+++oOX.  ",
"  .XOOo+++oOX.  ",
"..XXOo++@+oOXX..",
"XXXOo+++@++oOOXX",
"OOOoo++@@@++oOOO",
"OOo+++@@@@+++ooO",
"o+++@@@##@@++++o",
"+++@@##@##@@@+++",
"@@@@@@##@#@@@@++",
"+++++@@##@@@+++o",
"ooo+++@##@+++ooo",
"OOOoo+@@@@++oOOO",
"XXOOo++@@++oOXXX",
"..XXOo++@++oXX..",
"  .XOo++++oOX.  ",
"  ..XOo++ooOX.  "
};

/* EXPLOSION_5_HAND */
static char *explosion_5_hand[] = {
"16 16 6 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"o c #FFB700",
"O c #FF9425",
"+ c #FFE800",
"                ",
"                ",
"     .....      ",
"    .XXXXX......",
"    .XXOOXXXXXXX",
"    .XOOoOOOOXXO",
"   .XOOo+ooooOOo",
"   .XOoo++++++++",
"   .XOo++++++oo+",
"   .XOOoo+ooOOOO",
"   .XXOOOoOOOXXX",
"    .XXXOOXXX...",
"     ...XX...   ",
"        ..      ",
"                ",
"                "
};

/* EXPLOSION_6_ARM */
static char *explosion_6_arm[] = {
"16 16 8 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"o c #FFB700",
"O c #FF9425",
"+ c #FFE800",
"@ c #FFF66A",
"# c #FFFDD9",
"   ...          ",
" ..XXX...  .....",
".XXOOOXXX..XXXXX",
"XOOooOOOOXXOOOOO",
"OooooooooOOOoooo",
"oo++++ooooooooo+",
"+++@@+++o+o++++@",
"+@@##@++++++@###",
"+@####@++++@####",
"++@##@@++++++@@#",
"o+++@+++oooo+++@",
"Oooo+++ooOOooo++",
"XOoooooOOXXOOooo",
"XOOOOOOOX..XOOOO",
".XXXXXXX.  .XXXX",
" .......    ...."
};

/* EXPLOSION_6_CENTER */
static char *explosion_6_center[] = {
"16 16 8 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"o c #FFB700",
"O c #FF9425",
"+ c #FFE800",
"@ c #FFF66A",
"# c #FFFDD9",
" .XO+@##@++oOX. ",
".XOOo+@@@@+ooOX.",
"XXOo++@@@@@+oOOX",
"OOo++@@##@@++oOO",
"Ooo+@@####@@++oo",
"o++@@@####@@@+++",
"@@@#@@######@@##",
"#####@@##@##@###",
"#####@@##@@@@###",
"@@#@@@####@@@@#@",
"+@@+@#####@@++++",
"o+++@####@@+++oo",
"Ooo++@##@@++oooO",
"XOOo+@@@@++ooOOX",
".XXOo+@@@++oOXX.",
" .XOo++@@@+oOX. "
};

/* EXPLOSION_6_HAND */
static char *explosion_6_hand[] = {
"16 16 8 1 ",
"  c None",
". c #C80000",
"X c #FF3A27",
"o c #FFB700",
"O c #FF9425",
"+ c #FFE800",
"@ c #FFF66A",
"# c #FFFDD9",
"    ....        ",
"   .XXXX.. .....",
"  .XOOOOXX.XXXXX",
" .XOOoooOXXOOOOO",
" .XOo+++oOOooooO",
"  .XOo+++oo+++oo",
" .XOOo+++@@++@+o",
".XOooo+@###@@##+",
".XOo++@#####@##@",
".XOOo+++@##@+@++",
".XXOOo++++@++ooo",
" ..XXOoooo++oOOO",
"   ..XOOOoooOXXX",
"     .XXOOOOX...",
"      ..XXXX.   ",
"        ....    "
};

/* FLOWER1 */
static char *flower1[] = {
"16 16 5 1 ",
"  c None",
". c #008647",
"X c #3EC848",
"o c #7BFF5E",
"O c #E4FF5E",
"                ",
"   O            ",
"  O  O O        ",
"  o O   o    O  ",
"  o o   o   o   ",
"  X.X.  X.  X.  ",
"  . .   .   .   ",
"                ",
"                ",
"     O   O      ",
"   O o O  o     ",
" O o  o   o  O  ",
"  o   o   o o   ",
"  X.  X.  X.X.  ",
"  .   .   . .   ",
"                "
};

/* FLOWER2 */
static char *flower2[] = {
"16 16 5 1 ",
"  c None",
". c #008647",
"X c #3EC848",
"o c #7BFF5E",
"O c #E4FF5E",
"                ",
"   O     O      ",
" O  O  O  O  O  ",
"  O o O   o O   ",
"  o o o   o o   ",
"  X.X.X.  X.X.  ",
"  . . .   . .   ",
"                ",
"                ",
"   O     O      ",
"   o     O   O  ",
"  o  O O  o O   ",
"  o o   o o o   ",
"  X.X.  X.X.X.  ",
"  . .   . . .   ",
"                "
};

/* FLOWER3 */
static char *flower3[] = {
"16 16 13 1 ",
"  c None",
". c #007734",
"X c #00863A",
"o c #008647",
"O c #009641",
"+ c #3EC848",
"@ c #7BFF5E",
"# c #FF8573",
"$ c #E373FF",
"% c #73ABFF",
"& c #FFFCAC",
"* c #FFCDF7",
"= c #FFF7F6",
"                ",
"  XXXXXXX       ",
" X.......X      ",
" OX.....XO      ",
"  OOOOOOO       ",
"                ",
"                ",
"                ",
"  #   %   $     ",
" #=# %&% $*$    ",
"  #   %   $     ",
"  @   @   @     ",
"  +o  +o  +o    ",
"  o   o   o     ",
"                ",
"                "
};

/* GRASS_LEFT_BRODER */
static char *grass_left_broder[] = {
"16 16 6 1 ",
"  c #007734",
". c #00863A",
"X c #008641",
"o c #009641",
"O c #009B42",
"+ c #00AC4B",
"ooo++++X++++++++",
"..o+X++++++X++++",
" .o++++O+++++X++",
" .o+++X+++++O+++",
" .oO+++++O++++++",
" .o+++++++X+++++",
" .o+++O+X++++O+X",
" .o+X+++++++++++",
" .o++X+++++O++++",
" .o++++++++++X++",
" .o+++++O++++++X",
" .o++O+++++X++++",
" .o++++++++++O++",
" .oX++++++++++++",
" .o+++++X+++O+X+",
" .o++++X++++++++"
};

/* GRASS_LEFT */
static char *grass_left[] = {
"16 16 6 1 ",
"  c #007734",
". c #00863A",
"X c #008641",
"o c #009641",
"O c #009B42",
"+ c #00AC4B",
" .o+++++++X+++++",
" .o+++++++++O+++",
" .o+X+++X++X+O++",
" .o+++++++++++++",
" .o++++++++++++X",
" .oO+X++++O+++++",
" .o+X++O+++++X++",
" .o+++++++++++++",
" .o++++X++O+++++",
" .oO++++++++++++",
" .o+++++++X+++++",
" .o++X++X+++O++X",
" .o++++++O++++O+",
" .o++O++++++++++",
" .o+X+O++++X++++",
" .o++++++X+++++X"
};

/* GRASS_TOP_BORDER */
static char *grass_top_border[] = {
"16 16 6 1 ",
"  c #007734",
". c #00863A",
"X c #008641",
"o c #009641",
"O c #009B42",
"+ c #00AC4B",
"o.              ",
"o...............",
"oooooooooooooooo",
"+++++++++++++X++",
"+X+++++X++++++++",
"++++++++X++O+++X",
"+O+X++++++++++++",
"X+++++++++++O+++",
"++++++X++O++++X+",
"++++++++++++++++",
"+++O+X+++++++O++",
"+X+++++++++X++++",
"++++++O+O+++++++",
"++X++++++X++O+++",
"+++++O++++++++X+",
"+O++++X+++X+++++"
};

/* GRASS_TOP_LEFT_BORDER */
static char *grass_top_left_border[] = {
"16 16 6 1 ",
"  c #007734",
". c #00863A",
"X c #008641",
"o c #009641",
"O c #009B42",
"+ c #00AC4B",
" .o+++++++O+++++",
"..o++O+++X+++++X",
"ooo+++O++++X+O++",
"+O++X+++++++++++",
"++++++++X+++++X+",
"++++++++++++++++",
"+O+++++X++X+++++",
"++++O+++++++++++",
"+X++++++++++O+X+",
"++++++++++++++++",
"++++++++X++++++O",
"O+++X++O+++++O++",
"+++++X++O+++X+++",
"+++X+++++++++X++",
"++O+++O+++++++++",
"++++++++X+++++++"
};

/* GRASS_TOP_LEFT */
static char *grass_top_left[] = {
"16 16 6 1 ",
"  c #007734",
". c #00863A",
"X c #008641",
"o c #009641",
"O c #009B42",
"+ c #00AC4B",
"                ",
" ...............",
" .oooooooooooooo",
" .o+X+++++++O+++",
" .o+++++X+++++O+",
" .o+++++++++++++",
" .oO+++X++X+++O+",
" .o+++++++++++++",
" .o+++O+++++++X+",
" .o++++++++O++++",
" .o+++++X+++O+++",
" .o+X+++++++++++",
" .o++X++++++X+++",
" .oX+++++++++X++",
" .o+++++++++++++",
" .o++O++X+++++++"
};

/* GRASS_TOP */
static char *grass_top[] = {
"16 16 6 1 ",
"  c #007734",
". c #00863A",
"X c #008641",
"o c #009641",
"O c #009B42",
"+ c #00AC4B",
"                ",
"................",
"oooooooooooooooo",
"+++++++O++++X+++",
"+X++++++++++++++",
"++++X++++++++++X",
"++X++++O++X++X++",
"+O+++X+++O+O+++O",
"++++++++++++++++",
"++++++++X+++++++",
"++X+O+++++++O+++",
"X++++++X++++++O+",
"++++O++++X++++++",
"O+++++++++O+++++",
"+++++X++++++++X+",
"+++++++X+++++++X"
};

/* GRASS */
static char *grass[] = {
"16 16 3 1 ",
"  c #008641",
". c #009B42",
"X c #00AC4B",
"XXX XXXXXXXXX XX",
"XXXXXXXXXXXXXXXX",
"XXXXXXXX.XXXXXXX",
" XXXXX XXXXXXX.X",
"XXXXXXXXXXX XXX.",
"XXX.XXXXXXXXXX X",
"XXXXX.XXXXXX XXX",
" XXXXXX XX.XXXXX",
"XXX XXXXXXXXXXXX",
"X XXXXXXXXX.XXX.",
"XXXXXX.XXX XXXXX",
"X.XXXXXX XXXXXXX",
"XXXX XXXXXXXXX X",
"XXX.XXX.XXXXXXXX",
"XX XX XXXXXXXXX ",
"XXXXXXXX.XXX XXX"
};

/* WALL1 */
static char *wall1[] = {
"16 16 3 1 ",
"  c #081327",
". c #11264D",
"X c #515F78",
"XXXXXXXXXXXXXXX.",
"XXXXXXXXXXXXXX. ",
"XX............  ",
"XX............  ",
"XX............  ",
"XX............  ",
"XX............  ",
"XX............  ",
"XX............  ",
"XX............  ",
"XX............  ",
"XX............  ",
"XX............  ",
"XX............  ",
"X.              ",
".               "
};

/* WALL2 */
static char *wall2[] = {
"16 16 6 1 ",
"  c #000000",
". c #081327",
"X c #11264D",
"o c #243D6A",
"O c #515F78",
"+ c #798BAA",
"OOX+OOOOOOOOOOOX",
"OOOX+OOOOOOOOOX.",
"OOXX.oXXXXXXXX..",
"OOXXX.XXXXXXXX..",
"OOXXX.oXXXXXXX..",
"OOXXXX.XXXXXXX..",
"OOXXXX.oXXXXXX..",
"OOXXXXX.XXXXXX..",
"OOXXXXX.oXXXXX..",
"OOXXXXXX.XXXXX..",
"OOXXXXXX.oXXXX..",
"OOXXXXXXX.oXXX..",
"OOXXXXXXXX.oXX..",
"OOXXXXXXXXX.XX..",
"OX.......... ...",
"X............ .."
};

/* WALL3 */
static char *wall3[] = {
"16 16 6 1 ",
"  c #000000",
". c #081327",
"X c #11264D",
"o c #243D6A",
"O c #515F78",
"+ c #798BAA",
"OOX+OOOOOOO+XOOX",
"OOOX+OOOOOO+XOX.",
"OOXX.oXXXXo.XX..",
"OOXXX.XXXX.XXX..",
"OOXXX.oXXo.XXX..",
"OOXXXX.Xo.XXXX..",
"OOXXXo.o.XXXoo  ",
"OOXXo.X.XXo.....",
"O+oo.XX.o..XXX..",
"+X..oXXX.XXXXX..",
"XOXX.ooo.oXXXX..",
"OOXXo...X.oXXX..",
"OOXX.XXXXX.oXX..",
"OOXo.XXXXXX.oX..",
"OX. ........ ...",
"X.. ......... .."
};

/* Heart */
static char *heart[] = {
"15 15 6 1 ",
"  c None",
". c #000000",
"X c #AB0B0B",
"o c #DA0505",
"O c #D50909",
"+ c #FFFFFF",
"   ...   ...   ",
"  .OOO. .OOO.  ",
" .OOOOO.OOOOO. ",
" .OO+OOOOOOOO. ",
".OO+OOOOOOOOOO.",
".O+OOOOOOOOOOO.",
".oOOOOOOOOOOOO.",
" .XOOOOOOOOOX. ",
" .XXOOOOOOOXX. ",
"  .XXOOOOOXX.  ",
"   .XXOOOXX.   ",
"    .XXOXX.    ",
"     .XXX.     ",
"      .X.      ",
"       .       "
};
