/* ENEMY_1_STANDING */
static char * enemy_1_standing_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..oXX.. ",
"..oXXXX..",
".XX.X.XX.",
".XX.X.XX.",
"..XXXXX..",
" ..Xoo.. ",
"  ..X..  ",
"   .X.   ",
"   .O.   ",
"   ...   ",
"         "};

/* ENEMY_1_LEFT */
static char * enemy_1_left_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..XXo.. ",
"..XXXXo..",
".X.X.XXX.",
".X.X.XXX.",
"..XXXXX..",
" ..ooX.. ",
"  ..X..  ",
"   .X.   ",
"   .O.   ",
"   ...   ",
"         "};

/* ENEMY_1_RIGHT */
static char * enemy_1_right_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..oXX.. ",
"..oXXXX..",
".XXX.X.X.",
".XXX.X.X.",
"..XXXXX..",
" ..Xoo.. ",
"  ..X..  ",
"   .X.   ",
"   .O.   ",
"   ...   ",
"         "};

/* ENEMY_1_BACK */
static char * enemy_1_back_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..XXo.. ",
"..XXXXo..",
".XXXXXXX.",
".XXXXXXX.",
"..oXXXX..",
" ..oXX.. ",
"  ..X..  ",
"   .X.   ",
"   .O.   ",
"   ...   ",
"         "};

/* ENEMY_2_STANDING */
static char * enemy_2_standing_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..oXX.. ",
"..oXXXX..",
".XX.X.XX.",
".XX.X.XX.",
".XXXXXXX.",
"..XXooX..",
" ..XXX.. ",
"  ..X..  ",
"   .O.   ",
"   .O.   ",
"   ...   "};

/* ENEMY_2_LEFT */
static char * enemy_2_left_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..XXo.. ",
"..XXXXo..",
".X.X.XXX.",
".X.X.XXX.",
".XXXXXXX.",
"..XooX.. ",
" ..XXX.. ",
"  ..X..  ",
"   .O.   ",
"   .O.   ",
"   ...   "};

/* ENEMY_2_RIGHT */
static char * enemy_2_right_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..oXX.. ",
"..oXXXX..",
".XXX.X.X.",
".XXX.X.X.",
".XXXXXXX.",
"..XXooX..",
" ..XXX.. ",
"  ..X..  ",
"   .O.   ",
"   .O.   ",
"   ...   "};

/* ENEMY_2_BACK */
static char * enemy_2_back_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..XXo.. ",
"..XXXXo..",
".XXXXXXX.",
".XXXXXXX.",
".XXXXXXX.",
"..oXXXX..",
" ..oXX.. ",
"  ..X..  ",
"   .O.   ",
"   .O.   ",
"   ...   "};

/* ENEMY_3_STANDING */
static char * enemy_3_standing_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"         ",
"  .....  ",
" ..oXX.. ",
"..oXXXX..",
".XX.X.XX.",
".XX.X.XX.",
"..XXXXX..",
" ..Xoo.. ",
"  ..X..  ",
"   .X.   ",
"   .O.   ",
"   ...   "};

/* ENEMY_3_LEFT */
static char * enemy_3_left_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"         ",
"  .....  ",
" ..XXo.. ",
"..XXXXo..",
".X.X.XXX.",
".X.X.XXX.",
"..XXXXX..",
" ..ooX.. ",
"  ..X..  ",
"   .X.   ",
"   .O.   ",
"   ...   "};

/* ENEMY_3_RIGHT */
static char * enemy_3_right_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"         ",
"  .....  ",
" ..oXX.. ",
"..oXXXX..",
".XXX.X.X.",
".XXX.X.X.",
"..XXXXX..",
" ..Xoo.. ",
"  ..X..  ",
"   .X.   ",
"   .O.   ",
"   ...   "};

/* ENEMY_3_BACK */
static char * enemy_3_back_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"         ",
"  .....  ",
" ..XXo.. ",
"..XXXXo..",
".XXXXXXX.",
".XXXXXXX.",
"..oXXXX..",
" ..oXX.. ",
"  ..X..  ",
"   .X.   ",
"   .O.   ",
"   ...   "};

/* ENEMY_4_STANDING */
static char * enemy_4_standing_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..oXX.. ",
"..oXXXX..",
".XXXXXXX.",
".XX.X.XX.",
".XX.X.XX.",
"..XXXXX..",
" ..Xoo.. ",
"  ..X..  ",
"   .O.   ",
"   .O.   ",
"   ...   "};

/* ENEMY_4_LEFT */
static char * enemy_4_left_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..XXo.. ",
"..XXXXo..",
".XXXXXXX.",
".X.X.XXX.",
".X.X.XXX.",
"..XXXXX..",
" ..ooX.. ",
"  ..X..  ",
"   .O.   ",
"   .O.   ",
"   ...   "};

/* ENEMY_4_RIGHT */
static char * enemy_4_right_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..oXX.. ",
"..oXXXX..",
".XXXXXXX.",
".XXX.X.X.",
".XXX.X.X.",
"..XXXXX..",
" ..Xoo.. ",
"  ..X..  ",
"   .O.   ",
"   .O.   ",
"   ...   "};

/* ENEMY_4_BACK */
static char * enemy_4_back_xpm[] = {
"9 12 5 1",
" 	c None",
".	c #000000",
"X	c #E64040",
"o	c #EF6464",
"O	c #FFFFFF",
"  .....  ",
" ..XXo.. ",
"..XXXXo..",
".XXXXXXX.",
".XXXXXXX.",
".XXXXXXX.",
"..oXXXX..",
" ..oXX.. ",
"  ..X..  ",
"   .O.   ",
"   .O.   ",
"   ...   "};
